### ISSUE TITLE
how to run percysnapshot() synchromusly

### ISSUE THREAD

**Issue by amartanwar42** [percy/percy-webdriverio#255]
Hi Team,

I am running webdriverio tests in synchronous mode and when I am using percySnapshot() without await it is running asynchronously and creating a problem.

My use case:
on-page there are multiple images and I want to take a screenshot once all the images are loaded.
So to achieve that I have written below piece of code.

`snapShot(element, name) {
    if (type == 'visual') {
      element.waitForDisplayed({
        timeout: config.elementTimeout,
      });

      browser.waitUntil(function () {
        let resultStatus = false;
        let imagesCount = browser.execute(() => {
          return document.images.length;
        });
        console.log(`count is: ${imagesCount} `);
        let allLoaded = false;
        while (!allLoaded) {
          let count = 0;
          for (let i = 0; i < imagesCount; i++) {
            let loaded = browser.execute(i1 => {
              return document.images[i1].complete;
            }, i);

            if (loaded) count++;
            console.log(`total count: ${count}`);
          }
          // Breaking the while loop if all the images loading completes
          if (count == imagesCount) {
            console.log('=> All the Images are loaded...');
            console.log(`=>total count: ${count}`);
            resultStatus = true;
            break;
          } else {
            console.log('=> Not yet loaded...');
            console.log(`=>total not count: ${count}`);
            count = 0;
          }
          this.wait(2000);
          // setTimeout(waitUntilAllImageLoaded(), 300);
        }
        return resultStatus;
      });
      browser.percySnapshot(name);
    }
  }
`
still i can see screenshot without images. I beleive its because percySnapshot is running asynchronously.

Could u please help me to run percySnapshot synchronously.

**Comment by Robdel12** [comment]
Hey @amartanwar42! There's probably no nice way to use our SDK without adopting Node's `async` / `await`. Our SDK exports a pure async function, so it will always need an `await`. 

Another thing I noticed in the code snippet is: `browser.percySnapshot(name);` -- that's not valid (unless you made changes). `percySnapshot` takes the `browser` as the first arg: `await percySnapshot(browser, name)`

I'll close this issue since it won't really be possible to use it with sync mode, but feel free to keep commenting :)
