### ISSUE TITLE
TypeError: webdriverio_1.default is not a function using webdriverIO 7 and percy 2

### ISSUE THREAD

**Issue by mareru** [percy/percy-webdriverio#435]
I get this error using webdriverio v7 and latest Percy for visual testing:  

    [0-2] Error in "0: I can see page "Product Detail Page of the last product""
    TypeError: webdriverio_1.default is not a function
        at C:\WORK\AutomationPlayground\domain-work\webdriverio-tutorial-demo\src\step_definitions\visual\visual-steps.ts:7:45
        at Browser.call (C:\WORK\AutomationPlayground\domain-work\webdriverio-tutorial-demo\node_modules\webdriverio\build\commands\browser\call.js:43:16)
        at Browser.runCommandWithHooks (C:\WORK\AutomationPlayground\domain-work\webdriverio-tutorial-demo\node_modules\@wdio\sync\build\wrapCommand.js:105:34)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at Browser.runCommandWithHooks (C:\WORK\AutomationPlayground\domain-work\webdriverio-tutorial-demo\node_modules\@wdio\sync\build\wrapCommand.js:100:24)
        at Browser.wrapCommandFn (C:\WORK\AutomationPlayground\domain-work\webdriverio-tutorial-demo\node_modules\@wdio\sync\build\wrapCommand.js:67:44)
        at World.<anonymous> (C:\WORK\AutomationPlayground\domain-work\webdriverio-tutorial-demo\src\step_definitions\visual\visual-steps.ts:7:13)
        at World.executeSync (C:\WORK\AutomationPlayground\domain-work\webdriverio-tutorial-demo\node_modules\@wdio\sync\build\index.js:38:22)
        at C:\WORK\AutomationPlayground\domain-work\webdriverio-tutorial-demo\node_modules\@wdio\sync\build\index.js:69:68  

It doesn't even get to percy, so there is no screenshot there.  
All I do in the code is taking screenshot of the page:

    import percySnapshot from '@percy/webdriverio';
    import { Then } from '@cucumber/cucumber';
    Then(/^I can see page "([^"]*)"$/, (name: string) => {
      browser.waitForPageToLoad();
      browser.call(() => percySnapshot(name));
    });  
This is my `package.json` file:  

    "devDependencies": {
        "@cucumber/cucumber": "^7.1.0",
        "@percy/cli": "^1.0.0-beta.48",
        "@percy/webdriverio": "^2.0.0",
        "@types/chai": "^4.2.16",
        "@types/node": "^14.14.41",
        "@typescript-eslint/eslint-plugin": "^4.22.0",
        "@typescript-eslint/parser": "^4.22.0",
        "allure-commandline": "^2.13.8",
        "app-root-path": "^3.0.0",
        "chai": "^4.3.4",
        "eslint": "^7.24.0",
        "eslint-config-prettier": "^8.2.0",
        "eslint-plugin-prettier": "^3.4.0",
        "husky": "^6.0.0",
        "npm-run-all": "^4.1.5",
        "prettier": "^2.2.1",
        "ts-node": "^9.1.1",
        "tsconfig-paths": "^3.9.0",
        "typescript": "^4.2.4",
        "webdriverio": "^7.4.6"
      },
      "dependencies": {
        "@wdio/allure-reporter": "^7.4.2",
        "@wdio/cli": "^7.4.6",
        "@wdio/cucumber-framework": "^7.4.6",
        "@wdio/local-runner": "^7.4.6",
        "@wdio/selenium-standalone-service": "^7.4.2",
        "@wdio/spec-reporter": "^7.4.3",
        "@wdio/sync": "^7.4.6"
      }

Note:  
This used to work prior upgrading to webdriverIO v7 and percy v2.

**Comment by wwilsman** [comment]
Hi @mareru! You mentioned this worked prior to upgrading wdio and percy, have you tried upgrading only one at a time? I ask because your error does not mention percy in the stack trace, so it seems likely to be related to wdio 7. It was rewritten in TypeScript, so I feel like they might have changed some export paths (perhaps you need to change a default import somewhere into a namespace import).

**Comment by mareru** [comment]
@wwilsman thanks for reaching out!  
I upgraded both at the same time.  
It is really simple test and the line where it breaks is this one:  
`browser.call(() => percySnapshot(name));`  
I am importing `percySnaphot` like this `import percySnapshot from '@percy/webdriverio';` as shown in the example above.  
When I try to change it to `const {percySnapshot} = require('@percy/webdriverio');` like suggested in the percy docs, then I get the error in the same line as above but with different message:  
`TypeError: percySnapshot is not a function`  
Do you think I should report this to webdriverIO guys?

**Comment by wwilsman** [comment]
I wouldn't report this quiet yet until we rule out it actually being Percy. I would start by upgrading wdio first, or commenting out any percy related things and seeing if the error still persists. Generally, it's best practice to upgrade a single dependency at a time for situations like this so you know exactly which dependency caused any issue.

The original error you posted mentions line 7, but your example does not contain 7 lines. Is there a more complete reproducible example you could give? Judging by the error `webdriverio_1.default is not a function`, it looks like it could be coming from the compiled code (so the line number here may not point to the right line number in your source code).

The actual error message about the default export not being a function doesn't seem like it would come from this package since we definitely only have a single export with tests confirming this. Perhaps this is a TypeScript issue? Depending on how you have it configured, you may need to set `allowSyntheticDefaultImports: true` which should allow TS to work with normal node module's `module.exports` syntax.

**Comment by mareru** [comment]
I have run other tests not related to percy with webdriverIO v 7 and they don't have this error.  
I have tried to add `allowSyntheticDefaultImports: true` to the `tsconfig.json` file and it didn't help.  

I tried to run webdriverIO v6 with percy 2 and got this error.  
I tried to run webdriverIO v6 with percy 1 and it was successful. 

I tried to run webdriverIO v7 with percy1 and it was successful.  

Can we conclude it has to do with percy?

**Comment by mareru** [comment]
@wwilsman 
Here is the repo with my setup [github-repo](https://github.com/mareru/webdriverIO-shop-demo/tree/feature/upgrade-to-wdio7)  
Please can you check it out to see what am I missing there.  
Thanks!

**Comment by wwilsman** [comment]
Thanks for narrowing this down so we know for sure it's an issue in the Percy SDK. 

I'm still wondering if this has something to do with the TS compiler. We have passing type tests, but don't actually compile the code anywhere since it works with native Node. 

The error suggests that the default export is missing, but this SDK uses `module.exports` to export the function (not `module.exports.default`).

Try changing the Percy import to this?

``` typescript
import * as percySnapshot from '@percy/webdriverio';
```

Or maybe you can also set another TS compiler option to enable commonjs singular exports? I found this with a quick search:

```
 "esModuleInterop": true,
 "allowSyntheticDefaultImports": true,
```

**Comment by mareru** [comment]
Hi @wwilsman .  
I tried to do an import like this:  
`import * as percySnapshot from '@percy/webdriverio';`
  
But then my IntelliJ IDEA is complaining with the error: 
`TS2349: This expression is not callable.   Type 'typeof import("C:/webdriverio-tutorial-demo/node_modules/@percy/webdriverio/types/index")' has no call signatures.`  

Although, when I run the code it passes. 

I also tried setting this in `tsconfig.json:`
` "esModuleInterop": true,
 "allowSyntheticDefaultImports": true,`   
And I did the import like it was before:  
`import percySnapshot from '@percy/webdriverio';`

My IntelliJ IDEA did not complain and the test passed.  

I am not sure if this is any kind of issue in percy or maybe just the documentation could be updated.  
Either way, thanks a lot for your help since it works now. :)

**Comment by wwilsman** [comment]
Glad to hear you got it working with those settings!

I think this issue might go away when we eventually convert to ES modules. But in the meantime we might be able to work around it (and other compilers that might do this) by doing something like `module.exports.default = module.exports` so this works when the compiler expects the default property. 

I'll try this out when I'm back at a computer, but if it doesn't work I agree that adding some documentation around this would be the next best thing. 

I'll keep this issue open until one of those two things are done. 🙂
