### ISSUE TITLE
Could not take DOM snapshot WDIO v7

### ISSUE THREAD

**Issue by starbuck251** [percy/percy-webdriverio#470]
Hi I am trying to setup Percy with our application and having made the call under a sync cucumber step:

```
Home_Page.homePageIsVisible();
         browser.call(
            () => percySnapshot('Home Page')
        );
```

I am getting the following when running the test.
 
```
[percy] Could not take DOM snapshot "Home Page"
[percy] [object Object]

```

Would you have any idea why this might be the case?

I have installed:
 ```
 "@percy/cli": "^1.0.0-beta.50",
    "@percy/webdriverio": "^2.0.0",

"@wdio/allure-reporter": "^6.11.0",
    "@wdio/cli": "^7.2.3",
    "@wdio/config": "^7.2.1",
    "@wdio/cucumber-framework": "^7.2.1",
    "@wdio/local-runner": "^7.2.3",
    "@wdio/selenium-standalone-service": "^7.2.1",
    "@wdio/spec-reporter": "^7.2.1",
    "@wdio/static-server-service": "^7.2.1",
    "@wdio/sync": "^7.2.3",

```
Thanks in advance

**Comment by wwilsman** [comment]
Hey @starbuck251! This SDK actually [already uses `browser.call`](https://github.com/percy/percy-webdriverio/blob/master/index.js#L16). So perhaps the obfuscated error is related to nesting that method within itself?

As for why that error is obfuscated, it would have to be because it is already obfuscated when it get's caught, or the object being thrown is not a normal error object with a `message` property. So it would be hard to debug further without a reproducable example for us to debug.

**Comment by starbuck251** [comment]
Hi @wwilsman - thanks for your reply :) I returned to it this morning and had issues until I tried the combination

on wdio config I set up the service `'selenium-standalone' `
and then used it as you said:
` percySnapshot('Home Page')`

and now this is working fine, thanks again
